config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  resources :workouts do
    resources :exercises
  end
  resources :users
  
  authenticated :user do
    root 'workouts#index', as: "authenticated_root"
  end
  
  root 'welcome#index'
  
  match 'users/:id' => 'users#show', via: :get
  
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Setup accessible (or protected) attributes for your model
#attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :workouts
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :avatar) }
    end
  
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))
    
    redirect_to workout_path(@workout)
  end  
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :update, :edit, :destroy]
  def index
    @workouts = Workout.all.order("created_at DESC")
    
  end
  
  def show
  end
  
  def new
    @workout = Workout.new
  end
  
  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end  
  end
  
  def destroy
    @workout.destroy
    redirect_to root_path
  end
  
  private
  
  def workout_params
    params.require(:workout).permit(:date, :workout, :mood, :length)
  end
  
  def find_workout
    @workout = Workout.find(params[:id])
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.erb
<p>Exercise: <strong><%= exercise.name %></strong></p>
<p># of Sets: <strong><%= exercise.sets %></strong></p>
<p># of Reps: <strong><%= exercise.reps %></strong></p>

app/views/exercises/_form.html.erb
<%= simple_form_for([@workout, @workout.exercises.build]) do |f| %>
  <%= f.input :name %>
  <%= f.input :sets, placeholder: 'ex: 4' %>
  <%= f.input :reps, placeholder: 'ex: 10' %>
  <br />
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= render "shared/header" %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/shared/_footer.html.erb
<section class="footer">
  <div class="row">
    <div class="large-12 columns">
      Website by: <a href="http://www.justinbattenfield.me" target="_blank">Justin Battenfield</a>
    </div>
  </div>
</section>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Workout Logger", root_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li><%= link_to "New Log", new_workout_path %></li>
        <li class="has-dropdown">
          <a href="#">My Profile</a>
          <ul class="dropdown">
            <li><%= link_to "View Profile", current_user %></li>
            <li class="active"><a href="#">Active link in dropdown</a></li>
          </ul>
        </li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
  </section>
</nav>

app/views/users/index.html.erb
<%= @user.name %>

app/views/users/show.html.erb
<div class="row padded">
  <div class="large-12 columns">
    <h1>Your Profile</h1>
  </div>
</div>
<div class="row">
  <div class="large-8 medium-8 columns">
    <h2>Welcome, <%= @user.name %>!</h2>
    <p><%= link_to "Edit Profile", edit_user_registration_path, class: "button" %></p>
    
    
    <p>Email: <strong><%= @user.email %></strong></p>
    <p>Height: <strong><%= @user.height %></strong></p>
    <p>Weight: <strong><%= @user.weight %>lbs</strong></p>
    
    
  </div>
  
  <div class="large-3 medium-3 columns">
    <%= image_tag(current_user.avatar.url(:medium), class: "rounded") %>
  </div>
  
</div>

app/views/welcome/index.html.erb
<section class="banner stuff">
  <div class="row">
    <div class="large-12 columns">
      <h1>Never Forget A Workout Again.</h1>
    </div>
  </div>
  
  <div class="row">
    <div class="large-6 large-offset-3 columns">
      <h2>Ready To Start Logging?</h2>
    </div>
  </div>
  
  <div class="row">
    <div class="large-12 columns">
      <%= link_to "Start Logging Now", new_user_registration_path, class:"button-home" %>
    </div>
  </div>
  
</section>

app/views/workouts/_form.html.erb
  <%= simple_form_for @workout do |f| %>
    <%= f.input :date, label:"Date" %>
    <%= f.input :workout, label:"What Area Did You Workout?", placeholder: 'ex: Biceps' %>
    <%= f.input :mood, label:"How we're you feeling?", placeholder: 'ex: Jacked!' %>
    <%= f.input :length, label:"How long was the workout?", placeholder: 'ex: 1 Hour' %>      
    <%= f.button :submit %>
  <% end %>

app/views/workouts/edit.html.erb
<div class="row">
  <div class="large-10 large-offset-1 columns">
    <h1>Edit Workout</h1>
    <%= render 'form' %>

    <%= link_to "Cancel this log?", root_path %>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="row padded">
  <div class="large-12 columns">
    <h1>Your Workout Logs</h1>
  </div>
</div>
<div class="row">
  <div class="large-9 medium-9 columns">
    <% @workouts.each do |workout| %>
      <div class="workout-main">
        <h2><%= link_to workout.date.strftime("%B %d, %Y"), workout %></h2>
        <p class="workout"><%= workout.workout %></p>
        <p><%= link_to "View Workout", workout %></p>
    </div><!-- / end workout-main -->
    <% end %>
  </div>
  <div class="large-3 medium-3 columns sidebar">
    <%= image_tag(current_user.avatar.url(:medium), class: "rounded") %>
    <br />
    <%= link_to "New Log", new_workout_path, class: "button" %>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="row">
  <div class="large-10 large-offset-1 columns">
    <h1>Log A New Workout</h1>
    <%= render 'form' %>

    <%= link_to "Cancel this log?", root_path %>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="row padded">
  <div class="large-12 columns">
    <h1>Your <%= @workout.workout %> Workout</h1>
  </div>
</div>

<div class="row">
  <div class="large-6 medium-6 columns workout-show">
    <h2>Workout</h2>
    <p>Date: <strong><%= @workout.date %></strong></p>
    <p>Muscle Worked: <strong><%= @workout.workout %></strong></p>
    <p>Mood: <strong><%= @workout.mood %></strong></p>
    <p>Length of Workout: <strong><%= @workout.length %></strong></p>
  </div>
    
  <div class="large-6 medium-6 columns workout-show">
    <h2>Exercises</h2>
      <%= render @workout.exercises %>
  </div>
</div>  
    
  <div class="row">
    <div class="large-6 large-offset-3 columns">
      <h3>Add An Exercise</h3>
        <%= render "exercises/form" %>
  </div>
</div>

<div class="row">
  <div class="large-8 large-offset-2 columns">
    <%= link_to "Edit Log", edit_workout_path(@workout) %> |
    <%= link_to "Delete Log", workout_path(@workout), method: :delete, data: {confirm: "Are You Sure?"} %> |
    <%= link_to "Back To Logs", root_path %>
  </div>
</div>
 